pmtiles/loop.go
... since they are allowed in object names for some providers, and otherwise we get 404 error.
Also it is quite hard to debug as there is no log at all in this case. Suggestions:
- Return 400 Bad Request instead of 404
- Log `Malformed URL "foo"`
Note: PR made in the browser, untested, and my first line of Go, if we can call it that :laughing:
=> Allow dashes in file name

main.go, pmtiles/convert.go, pmtiles/convert_test.go, pmtiles/directory_test.go, pmtiles/loop.go, pmtiles/readerv2_test.go, pmtiles/show.go, pmtiles/subpyramid_test.go, pmtiles/upload.go
This PR replaces all the calls to `log.Fatal` or `panic` in the `pmtiles` package libraries with `error` responses. The `main.go` tool has been updated accordingly. This allows the `pmtiles` package to be used by other code without having to trap fatal errors.
=> Return errors instead of triggering fatal errors in library code

pmtiles/loop.go
This PR updates the `tilePattern` and `metadataPattern` regular expressions in `pmtiles/loop.pm` to allow undefined prefixes.
=> Update tilePattern and metadataPattern to allow leading prefixes

.github/workflows/test.yml, go.mod
Bumps the golang version from v1.17 (which did not work I think) to v1.18.
=> Use go v1.18

pmtiles/convert.go
Fixes #28.
There are several places where `File.write()` was called but the return value was ignored, meaning any failures would be silent.
Tested this locally by creating an artificially small filesystem and placing either the temp directory (via `--tempdir`) or output file in it to simulate disk full scenarios.
(below is for Mac OS, but there are [equivalent options](https://stackoverflow.com/a/16044420) for Linux)
```bash
hdiutil create -size 1m -fs 'Case-sensitive HFS+' -volname tinyfs tinyfs.dmg
hdiutil attach tinyfs.dmg -mountpoint tinyfs -nobrowse -readwrite
```
And some test cases, both of which complete successfully without this PR:
```console
$ go run main.go convert ./zurich_switzerland.mbtiles output.pmtiles --tmpdir tinyfs/
2023/02/03 11:13:09 convert.go:258: Querying total …
```
=> Ensure write failures are handled during conversion

README.md
This PR lists the URL routes used by pmtiles serve.
It also corrects an extension listed in a comment - the extension in the URL [needs to be mvt, not pbf](https://github.com/protomaps/go-pmtiles/blob/ec55f0194c438196844e66ee39040ae03a39ead3/pmtiles/server.go#L260)
=> docs: explain URL paths used by "pmtiles serve"

main.go, pmtiles/convert.go, pmtiles/directory.go, pmtiles/downloader.go, pmtiles/extract.go, pmtiles/extract_test.go, pmtiles/readerv2.go
* Experimental cli support for extracting a region from a larger archive, given a maxzoom and GeoJSON multipolygon region.
* Limited to credentialed buckets or local files now, public HTTP to come later
* Limited to a single download thread
* Change directory optimization to be faster and match Java implementation, affects root/leaf sizes
=> implement pmtiles extract [#31, #52]

main.go, pmtiles/bucket.go, pmtiles/bucket_test.go, pmtiles/extract.go, pmtiles/region.go, pmtiles/region_test.go, pmtiles/server.go, pmtiles/show.go
Also fixes maxzoom-only extracts and region parsing GeoJSON geometries not nested in Features.
=> Support public HTTP buckets

main.go, pmtiles/verify.go
* check the statistics and zoom levels in the header match the directories.
* if a clustered archive, verify the contents are in clustered order.
=> add pmtiles verify command [#65]

pmtiles/convert.go, pmtiles/convert_test.go
* error out if bounds is degenerate (zero or less area)
=> mbtiles convert: default bounds to world if bounds metadata missing [#60]

pmtiles/bucket.go, pmtiles/bucket_test.go
* this is to allow sdk v1 query params like s3ForcePathStyle, to work with Minio, etc.
=> Don't force aws sdk v2 for s3 buckets [#112]

caddy/Caddyfile, caddy/pmtiles_proxy.go, main.go, pmtiles/server.go, pmtiles/show.go, pmtiles/tilejson.go, pmtiles/tilejson_test.go
@mikeocool 
* This makes the `serve` command consistent with `show --tilejson` in taking a `--public-url` option for the base path. This is renamed from `--public-hostname` because it includes not just the hostname but also the protocol like `https://` and possibly a non-root path like `https://example.com/tiles`. 
* Also makes the above consistent where the TileJSON automatically adds the `{z}/{x}/{y}.{ext}` onto the end, inferring the tile type from the header, instead of having to present this yourself. @mikeocool any limitation in inferring this automatically? 
* Finally, the [TileJSON spec](https://github.com/mapbox/tilejson-spec/tree/master/3.0.0) has some optional properties `name`, `description`, `attribution`, `version` and we omit those keys if empty instead of passing a `null` …
=> Tilejson fixups

pmtiles/server.go
=> Better error message for tile 404s if header/dirs are cached.

.github/workflows/test.yml, pmtiles/bucket.go, pmtiles/bucket_test.go
Move `file://` url handling to a dedicated implementation instead of using gocloud. Also made it detect file changes so that the server will purge its cache when the file changes.
=> Implement native file bucket with change detection

.github/workflows/publish.yml
=> Docker multi platform support

caddy/pmtiles_proxy.go, go.mod, main.go, pmtiles/bucket.go, pmtiles/server.go, pmtiles/server_test.go
Set etag on tile, metadata, and tilejson responses. By default it uses the etag from the archive but you can opt into computing an etag per-resource with `--tile-etag` flag. The default archive etag behavior minimizes runtime overhead and is guaranteed to return a new etag when tile contents changes, but also ends up changing the etag (and purging intermediate caches) when the archive changes but an individual tile is the same between old and new archive.
This also implements `If-Match` and `If-None-Match` header handling by using go's built-in [`http.ServeContent`](https://pkg.go.dev/net/http#ServeContent) utility. As a side effect this also means that `pmtiles serve` now supports range requests within individual tiles.
=> Set etag on pmtiles serve responses

main.go, pmtiles/bucket.go, pmtiles/bucket_test.go, pmtiles/server.go, pmtiles/server_metrics.go, pmtiles/server_test.go
Add more prometheus metrics to pmtiles server:
- overall HTTP request duration, response size, and count by status/archive/handler
- underlying bucket request duration and count by status/archive
- directory cache size/limit, requests by hit/miss/inflight status
Also fixed a few things I found testing out the corner cases:
- translate any client cancellation exceptions to a 499 http response code, otherwise they are 500 and look like server failures in the stats
- return a 204 for OPTIONS requests since if there's a body the client will cancel reading it
- return a 405 for any other request methods besides GET/HEAD/OPTIONS - it doesn't seem like those should be supported?
The impact on performance seems to be negligible, tilesiege with 1.25m requests was around 37k qps before/after this …
=> Add more prometheus metrics

pmtiles/bucket.go
Enables the possibility to initialize FileBuckets from external packages
=> feat: add NewFileBucket func

pmtiles/bucket.go, pmtiles/bucket_test.go, pmtiles/server.go, pmtiles/server_test.go
@msbarry 
currently archives less than 16K don't work with file buckets (maybe same for HTTP depending on server)
The initial IO is for 16384 bytes to save roundtrips over the network. This is a useful optimization, and it doesn't seem worth special-casing non-network archives to do something different (do one IO for a few bytes to then get the exact length...)
However doing a `ReadAt` for 16384 bytes will read the entire archive and then raise an EOF error. This PR special cases range requests at offset 0 to allow shorter responses. I don't love this because it adds hidden hardcoded behavior based on offset=0. 
Alternative: add another boolean parameter to NewRangeReaderEtag that's like `allowShortResponse bool` to make this behavior explicit. Thoughts?
=> Fix 16k file bucket

main.go
Add default timeouts to the pmtiles HTTP server to prevent bad clients from keeping connections open.
=> Add timeouts to pmtiles server

pmtiles/bucket.go, pmtiles/bucket_test.go
* NewRangeReaderEtag for gocloud buckets does provider-specific operations for set/get etag and error.
* use generation ID as string etag for Google Cloud.
@akhenakh @msbarry
=> Support ETags for Azure and Google Cloud [#176, #177]

README.md
The GitHub README is intended for only developers building/forking this code.
=> migrate docs to docs.protomaps.com/pmtiles/cli [#80]

main.go, pmtiles/upload.go
Related to https://github.com/protomaps/go-pmtiles/issues/194
=> Update pmtiles upload --help

pmtiles/verify.go
* properly exit with status != 0 when invalid archive detected
* detect missing magic number instead of crashing
* detect mismatch between header data length and actual file length
* detect bounds area <= 0
=> Improve verify

pmtiles/verify.go
Detect cases of bad offset/length data in header, for tilemaker output: https://github.com/systemed/tilemaker/issues/794
=> Add additional verify checks for bad offset/length data [#202]

pmtiles/show.go
* `pmtiles show` now generates an encoded URL that will quickly take you to [PMTiles.io](http://pmtiles.io/) with your archive passed in.
* Perfect for 1-click links for inspecting PMTiles.
* Easily clickable from Visual Studio code or on macOS use `open -a <browser_name>`
* Future ideas below.
---
```bash
pmtiles show https://demo-bucket.protomaps.com/v4.pmtiles
```
Result
* Output looks something like:
pmtiles spec version: 3
tile type: mvt
...
xray: https://pmtiles.io/#url=https%3A%2F%2Fdemo-bucket.protomaps.com%2Fv4.pmtiles
---
For the case of a local file, the "xray: " log element is disabled.
```bash
pmtiles show pmtiles/fixtures/test_fixture_1.pmtiles
```
---
* https://pmtiles.io/tile/#zxy=1/0/0&url=https%3A%2F%2Fdemo-bucket.protomaps.com%2Fv4.pmtiles
* `pmtiles serve …
=> PMTiles Show: Generate an encoded URL that will quickly take you to PMTiles.io

pmtiles/tilejson.go
A minor change for those using raster based PMTiles
* For output of `pmtiles --tilejson`: Only add `vector_layers` if Tile Type is vector
=> Only add `vector_layers` if Tile Type is vector
